version: '3.5'

services:
  # app:
  #   image: cozy/test
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/sql:/tmp
